### ISSUE TITLE
Faint Whooshing Sound whenever you move.

### ISSUE THREAD

**Issue by SlimeKing77777** [pearuhdox/Cartographer#11]
Whenever the player (you) moves, you can hear a faint air like whooshing sound.

**Comment by pearuhdox** [comment]
I'll re-open this if there's more information that comes up but this is too vague to identify what might be causing this. Its also not guaranteed that this is caused by Cartographer. If you can find/tell me what you were using or what was happening in game during this issue, I can reopen and investigate.
