### ISSUE TITLE
ca.size_grow often does not stop magma cubes from splitting on death.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer#36]
I'm trying to make a magma cube with 1hp that won't split on death. I am using ca.size grow because it is supposed to stop mobs from splitting on death. However I frequently get magma cubes that split off of the custom mob on death.

**Comment by pearuhdox** [comment]
Issue resolved in most recent commit:

Verbose Explanation: The size slimes can have their health value set (it works but it is not perfect, requires a burst of Instant Health effect) so their health value will be set to 40 regardless of original scaling (they use absorption to track damage so that will still work correctly). If you manage to somehow do 41+ damage in a single hit to the mob, you will see the bug again. The number can be changed for individual users but I won't be setting it higher as it creates more of the damage particles when the player hits the finishing blow on the mob. In all cases 40 should be plenty high enough.
